"use client";

import Link from "next/link";
import { ShieldCheck, FileText, Mail, HeartHandshake } from "lucide-react";

import { Separator } from "@/components/ui/separator";

/* -------------------------------------------------------------------------- */
/*                                  Footer                                    */
/* -------------------------------------------------------------------------- */
/*
    PURPOSE
    ------------------------------------------------------------------
    Global footer displayed throughout the CIVICO platform.

    RESPONSIBILITIES
    ------------------------------------------------------------------
    • Display platform branding
    • Quick navigation links
    • AI transparency information
    • Platform commitment
    • Copyright notice
    • Government / AI disclaimer

    DOES NOT
    ------------------------------------------------------------------
    • Fetch backend data
    • Authenticate users
    • Execute business logic
    • Store application state
    • Call APIs

    Future Integrations
    ------------------------------------------------------------------
    • Dynamic government contact information
    • Constituency-specific links
    • Public transparency dashboard
    • Version information
*/
/* -------------------------------------------------------------------------- */

const quickLinks = [
  {
    label: "How It Works",
    href: "/about",
    icon: HeartHandshake,
  },
  {
    label: "Public Reports",
    href: "/reports/public",
    icon: FileText,
  },
  {
    label: "Privacy Policy",
    href: "/privacy",
    icon: ShieldCheck,
  },
  {
    label: "Contact MP Office",
    href: "/contact",
    icon: Mail,
  },
];

export default function Footer() {
  return (
    <footer className="mt-auto border-t bg-muted/30">
      <div className="container py-12">
        <div className="grid gap-10 md:grid-cols-3">
          {/* ---------------------------------------------------------- */}
          {/* Brand */}
          {/* ---------------------------------------------------------- */}

          <section className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary text-lg font-bold text-primary-foreground shadow-sm">
                C
              </div>

              <div>
                <h3 className="text-lg font-bold">CIVICO</h3>

                <p className="text-sm text-muted-foreground">
                  People's Priorities
                </p>
              </div>
            </div>

            <p className="max-w-sm text-sm leading-7 text-muted-foreground">
              An AI-powered civic intelligence platform that transforms
              multilingual citizen feedback into transparent, data-driven
              development priorities for constituency planning.
            </p>
          </section>

          {/* ---------------------------------------------------------- */}
          {/* Quick Links */}
          {/* ---------------------------------------------------------- */}

          <section>
            <h4 className="mb-4 text-sm font-semibold uppercase tracking-wide">
              Quick Links
            </h4>

            <nav aria-label="Footer Navigation" className="space-y-3">
              {quickLinks.map((link) => {
                const Icon = link.icon;

                return (
                  <Link
                    key={link.label}
                    href={link.href}
                    className="group flex items-center gap-3 text-sm text-muted-foreground transition-colors hover:text-foreground"
                  >
                    <Icon className="h-4 w-4 transition-transform group-hover:scale-105" />

                    <span>{link.label}</span>
                  </Link>
                );
              })}
            </nav>
          </section>

          {/* ---------------------------------------------------------- */}
          {/* Transparency */}
          {/* ---------------------------------------------------------- */}

          <section className="space-y-4">
            <h4 className="text-sm font-semibold uppercase tracking-wide">
              Transparency
            </h4>

            <div className="rounded-xl border bg-background p-5">
              <div className="mb-3 flex items-center gap-2">
                <ShieldCheck className="h-5 w-5 text-primary" />

                <span className="font-medium">AI Transparency</span>
              </div>

              <p className="text-sm leading-6 text-muted-foreground">
                Recommendations generated by CIVICO assist decision-making.
                Final planning and funding decisions remain under the authority
                of government officials.
              </p>
            </div>

            <div className="rounded-xl border bg-background p-5">
              <h5 className="mb-3 font-medium">Platform Commitment</h5>

              <ul className="space-y-2 text-sm leading-6 text-muted-foreground">
                <li>• Secure multilingual citizen submissions</li>
                <li>• AI-assisted issue classification</li>
                <li>• Transparent request tracking</li>
                <li>• Accessibility-first public service platform</li>
              </ul>
            </div>
          </section>
        </div>

        <Separator className="my-8" />

        {/* ---------------------------------------------------------- */}
        {/* Bottom Footer */}
        {/* ---------------------------------------------------------- */}

        <div className="flex flex-col items-center justify-between gap-4 text-center text-sm text-muted-foreground md:flex-row">
          <p>© {new Date().getFullYear()} CIVICO. All rights reserved.</p>

          <p>Powered by AI for Constituency Development Planning.</p>
        </div>
      </div>
    </footer>
  );
}
